FROM libresuite-dev-base AS deps

FROM deps AS packages

WORKDIR /app

COPY turbo.json ./
COPY packages/ ./packages/

RUN pnpm turbo run build --filter="@libresuite/secrets^..."

FROM packages AS builder

WORKDIR /app

COPY services/secrets/ ./services/secrets/

RUN pnpm --filter "@libresuite/secrets" run build

FROM builder AS development

WORKDIR /app

EXPOSE 4001

CMD ["pnpm", "--filter", "@libresuite/secrets", "dev"]
