FROM node:22-alpine

RUN apk add --no-cache libc6-compat

RUN corepack enable && corepack prepare pnpm@10.30.3 --activate

WORKDIR /app

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./

COPY apps/ ./apps/
COPY services/ ./services/
COPY packages/ ./packages/

RUN find apps services packages -type f ! -name "package.json" -delete

RUN pnpm install --frozen-lockfile

ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=true