FROM libresuite-dev-base AS deps

FROM deps AS packages

WORKDIR /app

COPY turbo.json ./
COPY packages/ ./packages/

RUN pnpm turbo run build --filter="@libresuite/gateway^..."

FROM packages AS builder

WORKDIR /app

COPY apps/gateway/ ./apps/gateway/

RUN pnpm --filter "@libresuite/gateway" run build

FROM builder AS development

WORKDIR /app

EXPOSE 4000

CMD ["pnpm", "--filter", "@libresuite/gateway", "dev"]
