FROM libresuite-dev-base AS deps

FROM deps AS packages

WORKDIR /app

COPY turbo.json ./
COPY packages/ ./packages/

RUN pnpm turbo run build --filter="@libresuite/users^..."

FROM packages AS builder

WORKDIR /app

COPY services/users/ ./services/users/

RUN pnpm --filter "@libresuite/users" db:generate
RUN pnpm --filter "@libresuite/users" run build

FROM builder AS development

WORKDIR /app

EXPOSE 4001

CMD ["sh", "-c", "pnpm --filter '@libresuite/users' db:migrate:deploy && pnpm --filter '@libresuite/users' dev"]
